identifier: carpo
name: carpo
url: https://cassioavi.la
type: mcu
arch: arm
toolchain:
  - zephyr
  - gnuarmemb
  - xtools
ram: 40
supported:
  - usb_device
  - ble
  - ieee802154
  - pwm
  - watchdog
  - gpio
